FROM python:3.13-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY pyproject.toml .

RUN pip install .[test,lint]

COPY . .

EXPOSE 8080

RUN chmod +x ./start.sh

CMD ["./start.sh"]
